package com.naomi.hostelmanagement.navigation

const val ROUTE_HOME = "Home"
//const val ROUTE_ABOUT = "about"
const val ROUTE_LOGIN = "login"
const val ROUTE_REGISTER = "register"
const val ROUTE_ADD_ROOM = "addproduct"
const val ROUTE_VIEW_ROOM = "viewproducts"
const val ROUTE_UPDATE_ROOM= "updateproduct"
const val ROUTE_VIEW_UPLOAD = "view_upload"
const val ROUTE_ROOMSIZE = "Home"
const val ROUTE_GALLERY = "gallery"
const val ROUTE_MPESA = "Mpesa"
const val ROUTE_BOOK = "book"
const val ROUTE_MAIN = "gallery"